net: error[E0038]: Weak pointer to parent trait from child
Provokes the following error:

 error[E0038]: the trait `Session` cannot be made into an object
  --> src/net/channel.rs:72:14
   |
72 |     session: SessionWeakPtr,
   |              ^^^^^^^^^^^^^^ `Session` cannot be made into an object
   |
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
  --> src/net/session/mod.rs:79:14
   |
76 | pub trait Session: Sync {
   |           ------- this trait cannot be made into an object...
...
79 |     async fn register_channel(
   |              ^^^^^^^^^^^^^^^^ ...because associated function `register_channel` has no `self` parameter
help: consider turning `register_channel` into a method by giving it a `&self` argument
   |
79 |     async fn register_channel(&self,
   |                               ++++++
help: alternatively, consider constraining `register_channel` so it does not apply to trait objects
   |
82 |         executor: Arc<Executor<'_, Self: Sized>>,
   |                                  +++++++++++++
-----------------------